- name: Create temp directory for build files
  ansible.builtin.file:
    path: /tmp/flightlog-frontend-docker
    state: directory

- name: Upload build directory
  ansible.builtin.copy:
    src: '{{ project_dir }}/frontend/build/'
    dest: /tmp/flightlog-frontend-docker/build

- name: Upload docker file
  ansible.builtin.copy:
    src: '{{ project_dir }}/frontend/Dockerfile'
    dest: /tmp/flightlog-frontend-docker/Dockerfile

- name: Upload nginx config
  ansible.builtin.copy:
    src: '{{ project_dir }}/frontend/nginx.conf'
    dest: /tmp/flightlog-frontend-docker/nginx.conf

- name: Docker login
  become: yes
  community.docker.docker_login:
    registry_url: https://ghcr.io/
    username: millarcalder
    password: '{{ secrets["docker_token"] }}'

- name: Build docker image
  become: yes
  community.docker.docker_image:
    build:
      path: /tmp/flightlog-frontend-docker
    name: ghcr.io/millarcalder/flightlog-frontend
    tag: '{{ image_tag }}'
    push: yes
    source: build
    debug: yes

- name: Docker logout
  become: yes
  community.docker.docker_login:
    state: absent

- name: Delete temp directory for build files
  ansible.builtin.file:
    path: /tmp/flightlog-frontend-docker
    state: absent
