- name: Setup flightlog webapp ingress
  kubernetes.core.k8s:
    state: present
    namespace: '{{ namespace }}'
    kubeconfig: ~/.kube/config
    name: flightlog-webapp
    resource_definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      spec:
        rules:
          - host: '{{ webapp_domain }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: flightlog-frontend
                      port:
                        number: 80

- name: Setup flightlog API ingress
  kubernetes.core.k8s:
    state: present
    namespace: '{{ namespace }}'
    kubeconfig: ~/.kube/config
    name: flightlog-api
    resource_definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      spec:
        rules:
          - host: '{{ api_domain }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: flightlog-api
                      port:
                        number: 80
