# This exists to build docker images on the target CPU architecture, so it is potentially a remote machine which is why
# we are copying files to the /tmp directory to buiild from

- name: Ensure the temp directory for build files is wiped before starting
  ansible.builtin.file:
    path: '{{ build_dir }}'
    state: absent

- name: Create temp directory for build files
  ansible.builtin.file:
    path: '{{ build_dir }}'
    state: directory

- name: Upload required files
  ansible.builtin.copy:
    src: '{{ file }}'
    dest: '{{ build_dir }}/...'
  loop: '{{ required_files }}'
  loop_control:
    loop_var: file

- name: Docker login
  become: yes
  community.docker.docker_login:
    registry_url: https://ghcr.io/
    username: millarcalder
    password: '{{ secrets["docker_token"] }}'

- name: Build Docker image
  become: yes
  community.docker.docker_image:
    build:
      path: '{{ build_dir }}'
    name: 'ghcr.io/millarcalder/{{ image_name }}'
    tag: '{{ image_tag }}'
    push: yes
    source: build

- name: Docker logout
  become: yes
  community.docker.docker_login:
    state: absent

- name: Delete temp directory for build files
  ansible.builtin.file:
    path: '{{ build_dir }}'
    state: absent
