[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "viewer"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools.dynamic]
dependencies = {"file"=["requirements.txt"]}

[project.scripts]
viewer = "viewer.cli:cli"
