- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /tmp/flightlog-frontend-docker
    state: directory

- name: Upload build directory
  ansible.builtin.copy:
    src: '{{ project_dir }}/frontend/build/'
    dest: /tmp/flightlog-frontend-docker/build

- name: Upload docker file
  ansible.builtin.copy:
    src: '{{ project_dir }}/frontend/docker/Dockerfile'
    dest: /tmp/flightlog-frontend-docker/Dockerfile

- name: Docker login
  become: yes
  community.docker.docker_login:
    registry_url: https://ghcr.io/
    username: millarcalder
    password: '{{ secrets["docker_token"] }}'

- name: Build docker image
  become: yes
  community.docker.docker_image:
    build:
      path: /tmp/flightlog-frontend-docker
    name: ghcr.io/millarcalder/flightlog-frontend
    tag: 'pi-{{ version }}'
    push: yes
    source: build
    debug: yes

- name: Docker logout
  become: yes
  community.docker.docker_login:
    state: absent
