- name: Deploy flightlog webapp
  kubernetes.core.k8s:
    name: flightlog-frontend
    state: present
    kubeconfig: ~/.kube/config
    namespace: '{{ namespace }}'
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flightlog-frontend-deployment
        labels:
          app: flightlog-frontend
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: flightlog-frontend
        template:
          metadata:
            labels:
              app: flightlog-frontend
          spec:
            imagePullSecrets:
              - name: flightlog-docker-registry-secret
            containers:
              - name: flightlog-frontend
                image: 'ghcr.io/millarcalder/flightlog-frontend:{{ version }}-{{ target_architecture }}'
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
                resources:
                  limits:
                    cpu: '500m'
                    memory: '500Mi'

- name: Deploy flightlog webapp http port
  kubernetes.core.k8s:
    state: present
    namespace: '{{ namespace }}'
    kubeconfig: ~/.kube/config
    name: flightlog-frontend
    resource_definition:
      apiVersion: v1
      kind: Service
      spec:
        selector:
          app: flightlog-frontend
        ports:
          - name: http
            port: 80
            targetPort: 80
