- name: Create temp directory for build files
  ansible.builtin.file:
    path: /tmp/flightlog-api-docker
    state: directory

- name: Upload Python wheel
  ansible.builtin.copy:
    src: '{{ project_dir }}/backend/dist/{{ wheel_name }}'
    dest: '/tmp/flightlog-api-docker/{{ wheel_name }}'

- name: Upload Docker file
  ansible.builtin.copy:
    src: '{{ project_dir }}/backend/Dockerfile'
    dest: /tmp/flightlog-api-docker/Dockerfile

- name: Docker login
  become: yes
  community.docker.docker_login:
    registry_url: https://ghcr.io/
    username: millarcalder
    password: '{{ secrets["docker_token"] }}'

- name: Build Docker image
  become: yes
  community.docker.docker_image:
    build:
      args:
        wheel_name: '{{ wheel_name }}'
      path: /tmp/flightlog-api-docker
    name: ghcr.io/millarcalder/flightlog-api
    tag: '{{ image_tag }}'
    push: yes
    source: build
    debug: yes

- name: Docker logout
  become: yes
  community.docker.docker_login:
    state: absent

- name: Delete temp directory for build files
  ansible.builtin.file:
    path: /tmp/flightlog-api-docker
    state: absent
