- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /tmp/flightlog-docker
    state: directory

- name: Upload python wheel
  ansible.builtin.copy:
    src: '../dist/{{ wheel_name }}'
    dest: '/tmp/flightlog-docker/{{ wheel_name }}'

- name: Upload docker file
  ansible.builtin.copy:
    src: ../docker/Dockerfile
    dest: /tmp/flightlog-docker/Dockerfile

- name: Docker login
  become: yes
  community.docker.docker_login:
    registry_url: https://ghcr.io/
    username: millarcalder
    password: '{{ secrets["docker_token"] }}'

- name: Build docker image
  become: yes
  community.docker.docker_image:
    build:
      args:
        wheel_name: '{{ wheel_name }}'
      path: /tmp/flightlog-docker
    name: ghcr.io/millarcalder/flightlog-api
    tag: 'pi-{{ version }}'
    push: yes
    source: build
    debug: yes

- name: Docker logout
  become: yes
  community.docker.docker_login:
    state: absent
