import os

DATABASE_URI = "postgresql+psycopg://root:secret@flightlog-db:5432/logbook"
PASSWORD_HASH_SECRET_KEY = (
    "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
)
PASSWORD_HASH_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

os.environ["DATABASE_URI"] = DATABASE_URI
os.environ["PASSWORD_HASH_SECRET_KEY"] = PASSWORD_HASH_SECRET_KEY
os.environ["PASSWORD_HASH_ALGORITHM"] = PASSWORD_HASH_ALGORITHM
os.environ["ACCESS_TOKEN_EXPIRE_MINUTES"] = str(ACCESS_TOKEN_EXPIRE_MINUTES)
