import os

DATABASE_URI = "sqlite:///testing.db"
IGC_FILES_BUCKET = "logbook-igc-files"
S3_ENDPOINT_URL = "http://flightlog-s3:9000/"
AWS_ACCESS_KEY_ID = "root"
AWS_SECRET_ACCESS_KEY = "1234qwer"
PASSWORD_HASH_SECRET_KEY = (
    "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
)
PASSWORD_HASH_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

os.environ["DATABASE_URI"] = DATABASE_URI
os.environ["IGC_FILES_BUCKET"] = IGC_FILES_BUCKET
os.environ["S3_ENDPOINT_URL"] = S3_ENDPOINT_URL
os.environ["AWS_ACCESS_KEY_ID"] = AWS_ACCESS_KEY_ID
os.environ["AWS_SECRET_ACCESS_KEY"] = AWS_SECRET_ACCESS_KEY
os.environ["PASSWORD_HASH_SECRET_KEY"] = PASSWORD_HASH_SECRET_KEY
os.environ["PASSWORD_HASH_ALGORITHM"] = PASSWORD_HASH_ALGORITHM
os.environ["ACCESS_TOKEN_EXPIRE_MINUTES"] = str(ACCESS_TOKEN_EXPIRE_MINUTES)
