- name: Build both backend & frontend docker containers for the viewer & logbook projects
  hosts: build_server

  pre_tasks:
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
    - name: What is the CPU architecture of this machine?
      include_role:
        name: cpu_architecture

  tasks:
    - name: Building docker images for the Python backends (FastAPI applications)
      include_role:
        name: build_docker_container
      vars:
        image_name: 'flightlog-{{ project }}-backend'
        version: '{{ lookup("file", project_dir+"/{{ project }}/backend/VERSION") }}'
        required_files:
          - '{{ project_dir }}/{{ project }}/backend/Dockerfile'
          - '{{ project_dir }}/{{ project }}/backend/dist/{{ project }}-{{ version }}-py3-none-any.whl'
      loop:
        - viewer
        - logbook
      loop_control:
        loop_var: project

    - name: Building docker images for the TypeScript frontends (React applications)
      include_role:
        name: build_docker_container
      vars:
        image_name: 'flightlog-{{ project }}-frontend'
        version: '{{ lookup("file", project_dir+"/{{ project }}/frontend/VERSION") }}'
        required_files:
          - '{{ project_dir }}/{{ project }}/frontend/Dockerfile'
          - '{{ project_dir }}/{{ project }}/frontend/build/'
      loop:
        - viewer
        - logbook
      loop_control:
        loop_var: project
