- name: Build docker containers on a remote host
  hosts: build_server
  pre_tasks:
    - name: Version
      ansible.builtin.include_role:
        name: version
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
  roles:
    - role: build_backend_container
      when: backend is defined and backend == "yes"
    - role: build_frontend_container
      when: frontend is defined and frontend == "yes"
