- name: Deploy to Kubernetes
  hosts: localhost
  pre_tasks:
    - name: Version
      ansible.builtin.include_role:
        name: version
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
  roles:
    - role: k8s_setup_namespace
    - role: k8s_deploy_frontend
      when: frontend is defined and frontend == "yes"
    - role: k8s_deploy_backend
      when: backend is defined and backend == "yes"
    - role: k8s_setup_ingress
