- name: Provision a Web Server
  hosts: viewer_webserver
  become: yes
  pre_tasks:
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
  roles:
    - role: wireguard
    - role: viewer_provision_vm
