- name: Deploy to a Web Server
  hosts: webserver
  pre_tasks:
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
    - name: What is the CPU architecture of this machine?
      include_role:
        name: what_is_my_cpu_architecture
  roles:
    - role: viewer_deploy_vm
