- name: Deploy to a Web Server
  hosts: webservers
  pre_tasks:
    - name: Version
      ansible.builtin.include_role:
        name: version
    - name: Load secrets
      include_vars:
        file: vault.yml
        name: secrets
  roles:
    - role: vm_deploy
