- name: Docker auth token
  set_fact:
    docker_auth_token: '{{ secrets["docker_username"] }}:{{ secrets["docker_token"] }}'

- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: '{{ namespace }}'
    state: present

- name: Docker registry secret
  vars:
    docker_registry_config:
      auths:
        ghcr.io:
          auth: '{{ docker_auth_token | b64encode }}'
  kubernetes.core.k8s:
    namespace: '{{ namespace }}'
    name: flightlog-docker-registry-secret
    resource_definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ docker_registry_config | to_json | b64encode }}'
