name: tests
run-name: Run tests on pull reqeusts and pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: docker compose up -d s3 init_minio_data
      - run: docker compose run dev /bin/sh -c "cd /workspace/viewer/backend && make developer-setup && make test"
      - run: docker compose run dev /bin/sh -c "cd /workspace/igc_parser && make developer-setup && make test"
      - run: docker compose down
