name: tests
run-name: Run tests on pull reqeusts and pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: spin up docker compose dependencies
        run: docker compose up -d s3 init_minio_data
      - name: run viewer backend tests
        run: docker compose run dev /bin/sh -c "cd /workspace/viewer/backend && make developer-setup && make test"
      - name: run igc-parser tests
        run: docker compose run dev /bin/sh -c "cd /workspace/igc_parser && make developer-setup && make test"
      - name: tear down docker compose dependencies
        run: docker compose down
